### ISSUE TITLE
Add wrapper to adjust design of polymerday web

### ISSUE THREAD

**Issue by Cazanon** [polymer-day/polymerday-twitter-timeline#1]
![twitter timeline design](https://cloud.githubusercontent.com/assets/9009500/19245629/69160ab4-8f22-11e6-82cd-4520f815609d.png)

**Comment by emartinpi** [comment]
@Cazanon I've created a new develop branch. Use this branch just in case you need a PR

**Comment by Cazanon** [comment]
Done.
Wait to accept PR

**Comment by emartinpi** [comment]
Done
